apiVersion: ko.io/v1alpha1
kind: NodeMaintenance
metadata:
  name: example-script
spec:
  paused: false
  allNodes: true
  script:
    inline: |
      #!/bin/sh
      set -eu
      echo "$GREETING from $NODE_NAME at $(date -u +%FT%TZ)"
      uname -a
    image: alpine:3.19
    timeoutSeconds: 600
    runOnHost: true
    env:
      - name: GREETING
        value: hello-world
  strategy:
    maxUnavailable: 2
  actions:
    - type: Cordon
    - type: Script
    - type: Uncordon
