// Code in this file would normally be generated by controller-gen
// (`make generate`). It is hand-written here so the project compiles without
// the codegen toolchain. The shape is identical to what controller-gen emits.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *NodeMaintenance) DeepCopyInto(out *NodeMaintenance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *NodeMaintenance) DeepCopy() *NodeMaintenance {
	if in == nil {
		return nil
	}
	out := new(NodeMaintenance)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeMaintenance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NodeMaintenanceList) DeepCopyInto(out *NodeMaintenanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]NodeMaintenance, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *NodeMaintenanceList) DeepCopy() *NodeMaintenanceList {
	if in == nil {
		return nil
	}
	out := new(NodeMaintenanceList)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeMaintenanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NodeMaintenanceSpec) DeepCopyInto(out *NodeMaintenanceSpec) {
	*out = *in
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			out.NodeSelector[k] = v
		}
	}
	if in.NodeNames != nil {
		out.NodeNames = append([]string(nil), in.NodeNames...)
	}
	if in.Actions != nil {
		out.Actions = make([]ActionSpec, len(in.Actions))
		for i := range in.Actions {
			in.Actions[i].DeepCopyInto(&out.Actions[i])
		}
	}
	out.Strategy = in.Strategy
}

func (in *NodeMaintenanceStatus) DeepCopyInto(out *NodeMaintenanceStatus) {
	*out = *in
	if in.Nodes != nil {
		out.Nodes = make([]NodeStatus, len(in.Nodes))
		for i := range in.Nodes {
			in.Nodes[i].DeepCopyInto(&out.Nodes[i])
		}
	}
	if in.StartTime != nil {
		t := *in.StartTime
		out.StartTime = &t
	}
	if in.CompletionTime != nil {
		t := *in.CompletionTime
		out.CompletionTime = &t
	}
}

func (in *ActionSpec) DeepCopyInto(out *ActionSpec) {
	*out = *in
	if in.DrainOptions != nil {
		out.DrainOptions = new(DrainOptions)
		in.DrainOptions.DeepCopyInto(out.DrainOptions)
	}
}

func (in *DrainOptions) DeepCopyInto(out *DrainOptions) {
	*out = *in
	if in.GracePeriodSeconds != nil {
		v := *in.GracePeriodSeconds
		out.GracePeriodSeconds = &v
	}
	if in.TimeoutSeconds != nil {
		v := *in.TimeoutSeconds
		out.TimeoutSeconds = &v
	}
}

func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	if in.CompletedActions != nil {
		out.CompletedActions = append([]string(nil), in.CompletedActions...)
	}
	if in.LastTransitionTime != nil {
		t := *in.LastTransitionTime
		out.LastTransitionTime = &t
	}
}
